// <auto-generated />
using System;
using Infrastructure.Persistence.SQLServer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.SQLServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppActionDaoAppPermissionDao", b =>
                {
                    b.Property<long>("ActionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionsId")
                        .HasColumnType("bigint");

                    b.HasKey("ActionsId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("ActionPermission", (string)null);
                });

            modelBuilder.Entity("AppActionDaoRoleDao", b =>
                {
                    b.Property<long>("ActionsId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActionsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RoleAction", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.AppActionDao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppAction");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.AppPermissionDao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AppPermissions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CitizenDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoordinateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdentityDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarriedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nni")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Occupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinateId");

                    b.HasIndex("IdentityDocumentId");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ConstituencyDao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CoordinateDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CountryDao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeIso")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DialCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CodeIso = "AF",
                            DialCode = "+93",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2L,
                            CodeIso = "ZA",
                            DialCode = "+27",
                            Name = "Afrique du Sud"
                        },
                        new
                        {
                            Id = 3L,
                            CodeIso = "AL",
                            DialCode = "+355",
                            Name = "Albanie"
                        },
                        new
                        {
                            Id = 4L,
                            CodeIso = "DZ",
                            DialCode = "+213",
                            Name = "Algérie"
                        },
                        new
                        {
                            Id = 5L,
                            CodeIso = "DE",
                            DialCode = "+49",
                            Name = "Allemagne"
                        },
                        new
                        {
                            Id = 6L,
                            CodeIso = "AD",
                            DialCode = "+376",
                            Name = "Andorre"
                        },
                        new
                        {
                            Id = 7L,
                            CodeIso = "AO",
                            DialCode = "+244",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8L,
                            CodeIso = "AI",
                            DialCode = "+1264",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9L,
                            CodeIso = "AQ",
                            DialCode = "672",
                            Name = "Antarctique"
                        },
                        new
                        {
                            Id = 10L,
                            CodeIso = "AG",
                            DialCode = "+1268",
                            Name = "Antigua-et-Barbuda"
                        },
                        new
                        {
                            Id = 11L,
                            CodeIso = "SA",
                            DialCode = "+966",
                            Name = "Arabie saoudite"
                        },
                        new
                        {
                            Id = 12L,
                            CodeIso = "AR",
                            DialCode = "+54",
                            Name = "Argentine"
                        },
                        new
                        {
                            Id = 13L,
                            CodeIso = "AM",
                            DialCode = "+374",
                            Name = "Arménie"
                        },
                        new
                        {
                            Id = 14L,
                            CodeIso = "AW",
                            DialCode = "+297",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 15L,
                            CodeIso = "AU",
                            DialCode = "+61",
                            Name = "Australie"
                        },
                        new
                        {
                            Id = 16L,
                            CodeIso = "AT",
                            DialCode = "+43",
                            Name = "Autriche"
                        },
                        new
                        {
                            Id = 17L,
                            CodeIso = "AZ",
                            DialCode = "+994",
                            Name = "Azerbaïdjan"
                        },
                        new
                        {
                            Id = 18L,
                            CodeIso = "BS",
                            DialCode = "+1242",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 19L,
                            CodeIso = "BH",
                            DialCode = "+973",
                            Name = "Bahreïn"
                        },
                        new
                        {
                            Id = 20L,
                            CodeIso = "BD",
                            DialCode = "+880",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 21L,
                            CodeIso = "BB",
                            DialCode = "+1246",
                            Name = "Barbade"
                        },
                        new
                        {
                            Id = 22L,
                            CodeIso = "BE",
                            DialCode = "+32",
                            Name = "Belgique"
                        },
                        new
                        {
                            Id = 23L,
                            CodeIso = "BZ",
                            DialCode = "+501",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24L,
                            CodeIso = "BJ",
                            DialCode = "+229",
                            Name = "Bénin"
                        },
                        new
                        {
                            Id = 25L,
                            CodeIso = "BM",
                            DialCode = "+1441",
                            Name = "Bermudes"
                        },
                        new
                        {
                            Id = 26L,
                            CodeIso = "BT",
                            DialCode = "+975",
                            Name = "Bhoutan"
                        },
                        new
                        {
                            Id = 27L,
                            CodeIso = "BY",
                            DialCode = "+375",
                            Name = "Biélorussie"
                        },
                        new
                        {
                            Id = 28L,
                            CodeIso = "BO",
                            DialCode = "+591",
                            Name = "Bolivie"
                        },
                        new
                        {
                            Id = 29L,
                            CodeIso = "BA",
                            DialCode = "+387",
                            Name = "Bosnie-Herzégovine"
                        },
                        new
                        {
                            Id = 30L,
                            CodeIso = "BW",
                            DialCode = "+267",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31L,
                            CodeIso = "BR",
                            DialCode = "+55",
                            Name = "Brésil"
                        },
                        new
                        {
                            Id = 32L,
                            CodeIso = "BN",
                            DialCode = "+673",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 33L,
                            CodeIso = "BG",
                            DialCode = "+359",
                            Name = "Bulgarie"
                        },
                        new
                        {
                            Id = 34L,
                            CodeIso = "BF",
                            DialCode = "+226",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 35L,
                            CodeIso = "BI",
                            DialCode = "+257",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 36L,
                            CodeIso = "KH",
                            DialCode = "+855",
                            Name = "Cambodge"
                        },
                        new
                        {
                            Id = 37L,
                            CodeIso = "CM",
                            DialCode = "+237",
                            Name = "Cameroun"
                        },
                        new
                        {
                            Id = 38L,
                            CodeIso = "CA",
                            DialCode = "+1",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 39L,
                            CodeIso = "CV",
                            DialCode = "+238",
                            Name = "Cap-Vert"
                        },
                        new
                        {
                            Id = 40L,
                            CodeIso = "CL",
                            DialCode = "+56",
                            Name = "Chili"
                        },
                        new
                        {
                            Id = 41L,
                            CodeIso = "CN",
                            DialCode = "+86",
                            Name = "Chine"
                        },
                        new
                        {
                            Id = 42L,
                            CodeIso = "CY",
                            DialCode = "+357",
                            Name = "Chypre"
                        },
                        new
                        {
                            Id = 43L,
                            CodeIso = "CO",
                            DialCode = "+57",
                            Name = "Colombie"
                        },
                        new
                        {
                            Id = 44L,
                            CodeIso = "KM",
                            DialCode = "+269",
                            Name = "Comores"
                        },
                        new
                        {
                            Id = 45L,
                            CodeIso = "CG",
                            DialCode = "+242",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 46L,
                            CodeIso = "CD",
                            DialCode = "+243",
                            Name = "Congo (RDC)"
                        },
                        new
                        {
                            Id = 47L,
                            CodeIso = "KP",
                            DialCode = "+850",
                            Name = "Corée du Nord"
                        },
                        new
                        {
                            Id = 48L,
                            CodeIso = "KR",
                            DialCode = "+82",
                            Name = "Corée du Sud"
                        },
                        new
                        {
                            Id = 49L,
                            CodeIso = "CR",
                            DialCode = "+506",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 50L,
                            CodeIso = "CI",
                            DialCode = "+225",
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 51L,
                            CodeIso = "HR",
                            DialCode = "+385",
                            Name = "Croatie"
                        },
                        new
                        {
                            Id = 52L,
                            CodeIso = "CU",
                            DialCode = "+53",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 53L,
                            CodeIso = "DK",
                            DialCode = "+45",
                            Name = "Danemark"
                        },
                        new
                        {
                            Id = 54L,
                            CodeIso = "DJ",
                            DialCode = "+253",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 55L,
                            CodeIso = "DM",
                            DialCode = "+1467",
                            Name = "Dominique"
                        },
                        new
                        {
                            Id = 56L,
                            CodeIso = "EG",
                            DialCode = "+20",
                            Name = "Égypte"
                        },
                        new
                        {
                            Id = 57L,
                            CodeIso = "AE",
                            DialCode = "+971",
                            Name = "Émirats arabes unis"
                        },
                        new
                        {
                            Id = 58L,
                            CodeIso = "EC",
                            DialCode = "+593",
                            Name = "Équateur"
                        },
                        new
                        {
                            Id = 59L,
                            CodeIso = "ER",
                            DialCode = "+291",
                            Name = "Érythrée"
                        },
                        new
                        {
                            Id = 60L,
                            CodeIso = "ES",
                            DialCode = "+34",
                            Name = "Espagne"
                        },
                        new
                        {
                            Id = 61L,
                            CodeIso = "EE",
                            DialCode = "+372",
                            Name = "Estonie"
                        },
                        new
                        {
                            Id = 62L,
                            CodeIso = "US",
                            DialCode = "+1",
                            Name = "États-Unis"
                        },
                        new
                        {
                            Id = 63L,
                            CodeIso = "ET",
                            DialCode = "+251",
                            Name = "Éthiopie"
                        },
                        new
                        {
                            Id = 64L,
                            CodeIso = "FJ",
                            DialCode = "+679",
                            Name = "Fidji"
                        },
                        new
                        {
                            Id = 65L,
                            CodeIso = "FI",
                            DialCode = "+358",
                            Name = "Finlande"
                        },
                        new
                        {
                            Id = 66L,
                            CodeIso = "FR",
                            DialCode = "+33",
                            Name = "France"
                        },
                        new
                        {
                            Id = 67L,
                            CodeIso = "GA",
                            DialCode = "+241",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 68L,
                            CodeIso = "GM",
                            DialCode = "+220",
                            Name = "Gambie"
                        },
                        new
                        {
                            Id = 69L,
                            CodeIso = "GH",
                            DialCode = "+233",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 70L,
                            CodeIso = "GR",
                            DialCode = "+30",
                            Name = "Grèce"
                        },
                        new
                        {
                            Id = 71L,
                            CodeIso = "GD",
                            DialCode = "+1473",
                            Name = "Grenade"
                        },
                        new
                        {
                            Id = 72L,
                            CodeIso = "GT",
                            DialCode = "+502",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 73L,
                            CodeIso = "GN",
                            DialCode = "+224",
                            Name = "Guinée"
                        },
                        new
                        {
                            Id = 74L,
                            CodeIso = "GQ",
                            DialCode = "+240",
                            Name = "Guinée équatoriale"
                        },
                        new
                        {
                            Id = 75L,
                            CodeIso = "GW",
                            DialCode = "+245",
                            Name = "Guinée-Bissau"
                        },
                        new
                        {
                            Id = 76L,
                            CodeIso = "GY",
                            DialCode = "+592",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 77L,
                            CodeIso = "HT",
                            DialCode = "+509",
                            Name = "Haïti"
                        },
                        new
                        {
                            Id = 78L,
                            CodeIso = "HN",
                            DialCode = "+504",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 79L,
                            CodeIso = "HU",
                            DialCode = "+36",
                            Name = "Hongrie"
                        },
                        new
                        {
                            Id = 80L,
                            CodeIso = "IN",
                            DialCode = "+91",
                            Name = "Inde"
                        },
                        new
                        {
                            Id = 81L,
                            CodeIso = "ID",
                            DialCode = "+62",
                            Name = "Indonésie"
                        },
                        new
                        {
                            Id = 82L,
                            CodeIso = "IQ",
                            DialCode = "+964",
                            Name = "Irak"
                        },
                        new
                        {
                            Id = 83L,
                            CodeIso = "IR",
                            DialCode = "+98",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 84L,
                            CodeIso = "IE",
                            DialCode = "+353",
                            Name = "Irlande"
                        },
                        new
                        {
                            Id = 85L,
                            CodeIso = "IS",
                            DialCode = "+354",
                            Name = "Islande"
                        },
                        new
                        {
                            Id = 86L,
                            CodeIso = "IL",
                            DialCode = "+972",
                            Name = "Israël"
                        },
                        new
                        {
                            Id = 87L,
                            CodeIso = "IT",
                            DialCode = "+39",
                            Name = "Italie"
                        },
                        new
                        {
                            Id = 88L,
                            CodeIso = "JM",
                            DialCode = "+1876",
                            Name = "Jamaïque"
                        },
                        new
                        {
                            Id = 89L,
                            CodeIso = "JP",
                            DialCode = "+81",
                            Name = "Japon"
                        },
                        new
                        {
                            Id = 90L,
                            CodeIso = "JO",
                            DialCode = "+962",
                            Name = "Jordanie"
                        },
                        new
                        {
                            Id = 91L,
                            CodeIso = "KZ",
                            DialCode = "+997",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 92L,
                            CodeIso = "KE",
                            DialCode = "+254",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 93L,
                            CodeIso = "KG",
                            DialCode = "+996",
                            Name = "Kirghizistan"
                        },
                        new
                        {
                            Id = 94L,
                            CodeIso = "KI",
                            DialCode = "+686",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 95L,
                            CodeIso = "KW",
                            DialCode = "+965",
                            Name = "Koweït"
                        },
                        new
                        {
                            Id = 96L,
                            CodeIso = "LA",
                            DialCode = "+856",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 97L,
                            CodeIso = "LS",
                            DialCode = "+266",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 98L,
                            CodeIso = "LV",
                            DialCode = "+371",
                            Name = "Lettonie"
                        },
                        new
                        {
                            Id = 99L,
                            CodeIso = "LB",
                            DialCode = "+961",
                            Name = "Liban"
                        },
                        new
                        {
                            Id = 100L,
                            CodeIso = "LR",
                            DialCode = "+231",
                            Name = "Libéria"
                        },
                        new
                        {
                            Id = 101L,
                            CodeIso = "LY",
                            DialCode = "+218",
                            Name = "Libye"
                        },
                        new
                        {
                            Id = 102L,
                            CodeIso = "LI",
                            DialCode = "+423",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 103L,
                            CodeIso = "LT",
                            DialCode = "+370",
                            Name = "Lituanie"
                        },
                        new
                        {
                            Id = 104L,
                            CodeIso = "LU",
                            DialCode = "+352",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 105L,
                            CodeIso = "MK",
                            DialCode = "+389",
                            Name = "Macédoine du Nord"
                        },
                        new
                        {
                            Id = 106L,
                            CodeIso = "MG",
                            DialCode = "+261",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 107L,
                            CodeIso = "MY",
                            DialCode = "+60",
                            Name = "Malaisie"
                        },
                        new
                        {
                            Id = 108L,
                            CodeIso = "MW",
                            DialCode = "+265",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 109L,
                            CodeIso = "MV",
                            DialCode = "+960",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 110L,
                            CodeIso = "ML",
                            DialCode = "+223",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 111L,
                            CodeIso = "MT",
                            DialCode = "+356",
                            Name = "Malte"
                        },
                        new
                        {
                            Id = 112L,
                            CodeIso = "MA",
                            DialCode = "+212",
                            Name = "Maroc"
                        },
                        new
                        {
                            Id = 113L,
                            CodeIso = "MU",
                            DialCode = "+230",
                            Name = "Maurice"
                        },
                        new
                        {
                            Id = 114L,
                            CodeIso = "MR",
                            DialCode = "+222",
                            Name = "Mauritanie"
                        },
                        new
                        {
                            Id = 115L,
                            CodeIso = "MX",
                            DialCode = "+52",
                            Name = "Mexique"
                        },
                        new
                        {
                            Id = 116L,
                            CodeIso = "FM",
                            DialCode = "+691",
                            Name = "Micronésie"
                        },
                        new
                        {
                            Id = 117L,
                            CodeIso = "MD",
                            DialCode = "+373",
                            Name = "Moldavie"
                        },
                        new
                        {
                            Id = 118L,
                            CodeIso = "MC",
                            DialCode = "+377",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 119L,
                            CodeIso = "MN",
                            DialCode = "+976",
                            Name = "Mongolie"
                        },
                        new
                        {
                            Id = 120L,
                            CodeIso = "ME",
                            DialCode = "+382",
                            Name = "Monténégro"
                        },
                        new
                        {
                            Id = 121L,
                            CodeIso = "MZ",
                            DialCode = "+258",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 122L,
                            CodeIso = "NA",
                            DialCode = "+264",
                            Name = "Namibie"
                        },
                        new
                        {
                            Id = 123L,
                            CodeIso = "NR",
                            DialCode = "+674",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 124L,
                            CodeIso = "NP",
                            DialCode = "+977",
                            Name = "Népal"
                        },
                        new
                        {
                            Id = 125L,
                            CodeIso = "NI",
                            DialCode = "+505",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126L,
                            CodeIso = "NE",
                            DialCode = "+227",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127L,
                            CodeIso = "NG",
                            DialCode = "+234",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128L,
                            CodeIso = "NO",
                            DialCode = "+47",
                            Name = "Norvège"
                        },
                        new
                        {
                            Id = 129L,
                            CodeIso = "NZ",
                            DialCode = "+64",
                            Name = "Nouvelle-Zélande"
                        },
                        new
                        {
                            Id = 130L,
                            CodeIso = "OM",
                            DialCode = "+968",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131L,
                            CodeIso = "UG",
                            DialCode = "+256",
                            Name = "Ouganda"
                        },
                        new
                        {
                            Id = 132L,
                            CodeIso = "UZ",
                            DialCode = "+998",
                            Name = "Ouzbékistan"
                        },
                        new
                        {
                            Id = 133L,
                            CodeIso = "PK",
                            DialCode = "+92",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 134L,
                            CodeIso = "PW",
                            DialCode = "+680",
                            Name = "Palaos"
                        },
                        new
                        {
                            Id = 135L,
                            CodeIso = "PS",
                            DialCode = "+970",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 136L,
                            CodeIso = "PA",
                            DialCode = "+507",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 137L,
                            CodeIso = "PG",
                            DialCode = "+675",
                            Name = "Papouasie-Nouvelle-Guinée"
                        },
                        new
                        {
                            Id = 138L,
                            CodeIso = "PY",
                            DialCode = "+595",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 139L,
                            CodeIso = "NL",
                            DialCode = "+31",
                            Name = "Pays-Bas"
                        },
                        new
                        {
                            Id = 140L,
                            CodeIso = "PE",
                            DialCode = "+63",
                            Name = "Pérou"
                        },
                        new
                        {
                            Id = 141L,
                            CodeIso = "PH",
                            DialCode = "+63",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 142L,
                            CodeIso = "PL",
                            DialCode = "+48",
                            Name = "Pologne"
                        },
                        new
                        {
                            Id = 143L,
                            CodeIso = "PT",
                            DialCode = "+351",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 144L,
                            CodeIso = "QA",
                            DialCode = "+974",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 145L,
                            CodeIso = "RO",
                            DialCode = "+40",
                            Name = "Roumanie"
                        },
                        new
                        {
                            Id = 146L,
                            CodeIso = "GB",
                            DialCode = "+44",
                            Name = "Royaume-Uni"
                        },
                        new
                        {
                            Id = 147L,
                            CodeIso = "RU",
                            DialCode = "+7",
                            Name = "Russie"
                        },
                        new
                        {
                            Id = 148L,
                            CodeIso = "RW",
                            DialCode = "+250",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 149L,
                            CodeIso = "LC",
                            DialCode = "+1-758",
                            Name = "Sainte-Lucie"
                        },
                        new
                        {
                            Id = 150L,
                            CodeIso = "VC",
                            DialCode = "+1-784",
                            Name = "Saint-Vincent-et-les-Grenadines"
                        },
                        new
                        {
                            Id = 151L,
                            CodeIso = "WS",
                            DialCode = "+685",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 152L,
                            CodeIso = "SM",
                            DialCode = "+590",
                            Name = "Saint-Marin"
                        },
                        new
                        {
                            Id = 153L,
                            CodeIso = "ST",
                            DialCode = "+239",
                            Name = "Sao Tomé-et-Principe"
                        },
                        new
                        {
                            Id = 154L,
                            CodeIso = "SN",
                            DialCode = "+221",
                            Name = "Sénégal"
                        },
                        new
                        {
                            Id = 155L,
                            CodeIso = "RS",
                            DialCode = "+381",
                            Name = "Serbie"
                        },
                        new
                        {
                            Id = 156L,
                            CodeIso = "SC",
                            DialCode = "+248",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 157L,
                            CodeIso = "SL",
                            DialCode = "+232",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 158L,
                            CodeIso = "SG",
                            DialCode = "+65",
                            Name = "Singapour"
                        },
                        new
                        {
                            Id = 159L,
                            CodeIso = "SK",
                            DialCode = "+421",
                            Name = "Slovaquie"
                        },
                        new
                        {
                            Id = 160L,
                            CodeIso = "SI",
                            DialCode = "+386",
                            Name = "Slovénie"
                        },
                        new
                        {
                            Id = 161L,
                            CodeIso = "SO",
                            DialCode = "+252",
                            Name = "Somalie"
                        },
                        new
                        {
                            Id = 162L,
                            CodeIso = "SD",
                            DialCode = "+249",
                            Name = "Soudan"
                        },
                        new
                        {
                            Id = 163L,
                            CodeIso = "SS",
                            DialCode = "+211",
                            Name = "Soudan du Sud"
                        },
                        new
                        {
                            Id = 164L,
                            CodeIso = "LK",
                            DialCode = "+94",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 165L,
                            CodeIso = "SE",
                            DialCode = "+46",
                            Name = "Suède"
                        },
                        new
                        {
                            Id = 166L,
                            CodeIso = "CH",
                            DialCode = "+41",
                            Name = "Suisse"
                        },
                        new
                        {
                            Id = 167L,
                            CodeIso = "SR",
                            DialCode = "+597",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 168L,
                            CodeIso = "SY",
                            DialCode = "+963",
                            Name = "Syrie"
                        },
                        new
                        {
                            Id = 169L,
                            CodeIso = "TJ",
                            DialCode = "+992",
                            Name = "Tadjikistan"
                        },
                        new
                        {
                            Id = 170L,
                            CodeIso = "TZ",
                            DialCode = "+255",
                            Name = "Tanzanie"
                        },
                        new
                        {
                            Id = 171L,
                            CodeIso = "TD",
                            DialCode = "+235",
                            Name = "Tchad"
                        },
                        new
                        {
                            Id = 172L,
                            CodeIso = "CZ",
                            DialCode = "+420",
                            Name = "Tchéquie"
                        },
                        new
                        {
                            Id = 173L,
                            CodeIso = "TH",
                            DialCode = "+66",
                            Name = "Thaïlande"
                        },
                        new
                        {
                            Id = 174L,
                            CodeIso = "TL",
                            DialCode = "+670",
                            Name = "Timor oriental"
                        },
                        new
                        {
                            Id = 175L,
                            CodeIso = "TG",
                            DialCode = "+228",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 176L,
                            CodeIso = "TO",
                            DialCode = "+676",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 177L,
                            CodeIso = "TT",
                            DialCode = "+1-868",
                            Name = "Trinité-et-Tobago"
                        },
                        new
                        {
                            Id = 178L,
                            CodeIso = "TN",
                            DialCode = "+216",
                            Name = "Tunisie"
                        },
                        new
                        {
                            Id = 179L,
                            CodeIso = "TM",
                            DialCode = "+993",
                            Name = "Turkménistan"
                        },
                        new
                        {
                            Id = 180L,
                            CodeIso = "TR",
                            DialCode = "+90",
                            Name = "Turquie"
                        },
                        new
                        {
                            Id = 181L,
                            CodeIso = "TV",
                            DialCode = "+688",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 182L,
                            CodeIso = "UA",
                            DialCode = "+380",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 183L,
                            CodeIso = "UY",
                            DialCode = "+598",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 184L,
                            CodeIso = "VU",
                            DialCode = "+678",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 185L,
                            CodeIso = "VE",
                            DialCode = "+58",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 186L,
                            CodeIso = "VN",
                            DialCode = "+84",
                            Name = "Viêt Nam"
                        },
                        new
                        {
                            Id = 187L,
                            CodeIso = "YE",
                            DialCode = "+967",
                            Name = "Yémen"
                        },
                        new
                        {
                            Id = 188L,
                            CodeIso = "ZM",
                            DialCode = "+260",
                            Name = "Zambie"
                        },
                        new
                        {
                            Id = 189L,
                            CodeIso = "ZW",
                            DialCode = "+263",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ElectorDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ConstituencyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DesactivationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ElectorNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("ElectorNumber")
                        .IsUnique()
                        .HasFilter("[ElectorNumber] IS NOT NULL");

                    b.ToTable("Electors");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.FiliationDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitoyenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Proof")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("RelatifId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeLien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RelatifId");

                    b.HasIndex("CitoyenId", "RelatifId", "TypeLien")
                        .IsUnique();

                    b.ToTable("Filiations");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.IdentityDocumentDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("IdentityDocuments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RefreshTokenDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Expiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RegistrationRequestDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastUpdaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonForRejection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTimeOffset>("SoumissionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("LastUpdaterId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RoleDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.SupportingDocumentsDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateUpload")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<Guid>("RegistrationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupportingDocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlStockage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationRequestId");

                    b.ToTable("SupportingDocuments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserDao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Civility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DisabledDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleDao", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUserType")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("AppActionDaoAppPermissionDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.AppActionDao", null)
                        .WithMany()
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.AppPermissionDao", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppActionDaoRoleDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.AppActionDao", null)
                        .WithMany()
                        .HasForeignKey("ActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.RoleDao", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CitizenDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.CoordinateDao", "Coordinate")
                        .WithMany()
                        .HasForeignKey("CoordinateId");

                    b.HasOne("Infrastructure.Persistence.Entities.IdentityDocumentDao", "IdentityDocument")
                        .WithMany()
                        .HasForeignKey("IdentityDocumentId");

                    b.Navigation("Coordinate");

                    b.Navigation("IdentityDocument");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ConstituencyDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.ConstituencyDao", "ConstituencyParent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("ConstituencyParent");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CoordinateDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.CountryDao", "HostCountry")
                        .WithMany("Coordinates")
                        .HasForeignKey("CountryId");

                    b.Navigation("HostCountry");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ElectorDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.CitizenDao", "Citizen")
                        .WithOne("Elector")
                        .HasForeignKey("Infrastructure.Persistence.Entities.ElectorDao", "CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.ConstituencyDao", "Constituencies")
                        .WithMany("Voters")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");

                    b.Navigation("Constituencies");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.FiliationDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.CitizenDao", "Citoyen")
                        .WithMany("FiliationsAsSubject")
                        .HasForeignKey("CitoyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.CitizenDao", "Relatif")
                        .WithMany("FiliationsAsRelative")
                        .HasForeignKey("RelatifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citoyen");

                    b.Navigation("Relatif");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RefreshTokenDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RegistrationRequestDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", "Author")
                        .WithMany("CreatedRegistrationRequests")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Infrastructure.Persistence.Entities.CitizenDao", "Citizen")
                        .WithMany("RegistrationRequests")
                        .HasForeignKey("CitizenId");

                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", "LastUpdater")
                        .WithMany("UpdatedRegistrationRequests")
                        .HasForeignKey("LastUpdaterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Citizen");

                    b.Navigation("LastUpdater");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.SupportingDocumentsDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.RegistrationRequestDao", "RegistrationRequest")
                        .WithMany("SupportingDocuments")
                        .HasForeignKey("RegistrationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistrationRequest");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserRoleDao", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.RoleDao", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.RoleDao", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserDao", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CitizenDao", b =>
                {
                    b.Navigation("Elector");

                    b.Navigation("FiliationsAsRelative");

                    b.Navigation("FiliationsAsSubject");

                    b.Navigation("RegistrationRequests");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ConstituencyDao", b =>
                {
                    b.Navigation("Voters");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.CountryDao", b =>
                {
                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RegistrationRequestDao", b =>
                {
                    b.Navigation("SupportingDocuments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserDao", b =>
                {
                    b.Navigation("CreatedRegistrationRequests");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UpdatedRegistrationRequests");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
